spring.application.name: prova-9-sample-spring-boot-app-k8s

springdoc.show-actuator: true

management.endpoints.web.exposure.include: '*'
management:
  endpoint.health:
    show-details: always
    probes:
      enabled: true