apiVersion: apps/v1
kind: Deployment
metadata:
  name: prova-9-sample-spring-boot-app-k8s
spec:
  selector:
    matchLabels:
      app: prova-9-sample-spring-boot-app-k8s
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
      labels:
        app: prova-9-sample-spring-boot-app-k8s
    spec:
      containers:
        - name: prova-9-sample-spring-boot-app-k8s
          image: d1-cnoe/prova-9-sample-spring-boot-app-k8s
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/readiness
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          resources:
            limits:
              memory: 1024Mi
---
apiVersion: v1
kind: Service
metadata:
  name: prova-9-sample-spring-boot-app-k8s
spec:
  type: NodePort
  selector:
    app: prova-9-sample-spring-boot-app-k8s
  ports:
    - port: 8080
      nodePort: 30000