name: JIB container publish

on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: JIB container build and publish
        uses: MathieuSoysal/jib-container-publish.yml@v2.1.5
        with:
          PASSWORD: ${{ secrets.THE_TOKEN }}
          java-version: 21
